repos:
  - repo: local
    hooks:
      - id: block-secrets-file
        name: Prevent committing secrets.toml
        entry: bash -c 'if git diff --cached --name-only | grep -qE "(^|/)secrets\.toml$"; then echo "🚫 secrets.toml is blocked from being committed."; exit 1; fi'
        language: system
        types: [file]
