
[credentials.usernames.chloe]
  email = "chloe@valencevibrations.com"
  name = "Chloe"
  password = "$2y$10$5.p2x3bqM0xf0kTyBo.8we1EC64/uRTJkQVMHOip/W5PyDP2OJfHi"

[credentials.usernames.shannon]
  email = "shannon@valencevibrations.com"
  name = "Shannon"
  password = "$2y$10$/FRrAFG1M2JnT4GbqQFfMOCdomhSsaL82uYED72QU4jLVcBV1r8YK"

[credentials.usernames.kaleb]
  email = "kaleb.ortiz@goacsi.com"
  name = "Kaleb"
  password = "$2y$10$okESTRtLH3wHBmUHvtVPr.ypuMQOstkSWpBbylr.5LlIu.cRvdzP2"

[credentials.usernames.cesar]
  email = "cesar@goacsi.com"
  name = "Cesar"
  password = "$2y$10$GRECQDMUNqoEMrCs2rQBFOjge2eRxR07/3/ulOgJA.yIXTCWqF2De"

[credentials.usernames.mark]
  email = "mark@goacsi.com"
  name = "Mark"
  password = "$2y$10$5O/GLKTVanJqLhawqYuKMOavxr3TBvERGJ1TeyjqF62w8/zna17OC"

[credentials.usernames.fabian]
  email = "fabian@goacsi.com"
  name = "Fabian"
  password = "$2y$10$0VlWts/uCyx/ARBkoef2i.MTNCHg2rYmlrKTMlmgjKbEqcfTfcRKG"

[cookie]
  name = "acsi_dashboard_session"
  key = "`8;=s.NsT5|2"
  expiry_days = 7

[auto_hash]
auto_hash = false

[firebase]
type = "service_account"
project_id = "valence-acsi-dashboard"
private_key_id = "e8065d1b80ec392a02a0639b048d8cf940b7f52e"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCVnL8z8fRM500W\ncr34Vjm3SE/8MbqiqYHNzfl0BYXz0Kx/GrB7oSCAWYyYBACya32ATMNWmHVLCIjt\nuwZPbg2P/0+ausc9IaAxaSWtGWL2TJIUk1+FAgjcQLasyMyFa84DVQ/tqGfMp5Rd\nIgz+PD0KBcApMn5g0ACbMjxcyCde6dHMZU/CvR5a79rsW1vOvgIaVSEsu5xKEWCt\nvF6kBms2qmu/boRADHTK8kNrhsmBC72EDwoOdMDdK7Wc5eVp9cmKicmPMeJU1yBA\nwoCL558GnYSJFvAGaAlYT5bF8p1H4etLfLL0KX4Pv0nrEnqLJx3PJp7qQtXbACFI\nbbV5wTLZAgMBAAECggEABkl593LZc0ndAW588SyebEdLpStpzmAVJlLbgragtGg2\nd3jlpaxVs08QC2tPpC/ELFoNc1wgwbBwIJ1VXI0hYMW30Ka8rKL3Glxyyt1gPT1m\nfhrbTrmRKcBGbOhbP9gR5i3y52fGROFd6LP/m8doQT2Qn6qRiPv0qpDn3HZEwUY9\nqf6Bwe6Rcko3aZFpziOUuaAYkD0/HJn28zn3+U/n+mczbIJt4CsEVnHGgt35Fj+W\nX7QVVm56c48F93eM7ZYBFIyHd67ZE53b7M8GFA8WYRDx0eSR9+YbToNNnDe5fRh6\n+78XOgV73r7daeDqS7CRRTF2g0/jbtskGCecvLIYIQKBgQDEAyinIdKStrYtV4M6\nxMriBB8l00qfipV7307H96D/HbCYCVoct7YiBqNDn/QhdwVPeT1ZXFDTpaKLf2cz\nCz7/ZXzhSsUwPSqaYrSKBQVpn0U/iQfMwLpTQzKUmdGG0TLYzKs7VqdGQoMuPxMY\n6d5JvVQS9/VErMK0S1ID7RxBVQKBgQDDZlDyNW3bUVcUaRQNAIZ5BrQyuEYaIti0\ni2ohbiCD3Y+AcypOYQbkYrHQsyxozwdNM61XOYA+Fb+uQK1S5EwzUbSZDJ8xZgqi\n/lCfa3I/zOpQQ1Ki8yB+EMfZgJhIxPSYhDPo6ve5XFF5Hb6rAkAAVro4Nt3zdWQB\nyIXEHKX7dQKBgHdAdLs6GKKqBqwPUgevMr/PQiQBKKVn6woyEfwW7BxKM+ZLykcu\nfeC1qR67cgvqHZD8char04DwhLPaDy8+6FT5qcBnfRCcJg9Hfg96fpCEFd1RwS0R\nFEsT1vIRoyginozH+GVhkuNsE+NO/I9ruZGjXkMsGExvzwVhzcQVvdsBAoGATInc\ndTOWh40SBg2u6/Tjt653kVJ7KyuxJO9jMBsaI2z7E/6IeNEqyPUb37r/T0KhAo2W\nfY8pe6g7P/9XpRuF+agsjLLT/J6S1gu1+uw0gWc79RqZ2PhRJvBdyAXGIOL9SGyo\nhLjdNj9CLqYHFKc5+KgAI5riT8YQ2V35f7sVDS0CgYBIhUCDoeVtlDZPQXDml3vm\neT5sUSGLLvK5D4LAMyYOrMM6X8OFGLE8KM3ZlAM6XlPnDfA3fRdYa9h9sT1tLMal\n7LVOFKT1XSC1dOhl+6DO/gRWDesIwQqwst/Y9LiqJPou0XD6ZDE7LV098e0MxrIU\nQYehhUieiv249VJgGNs5QA==\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@valence-acsi-dashboard.iam.gserviceaccount.com"
client_id = "105800006164158152927"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40valence-acsi-dashboard.iam.gserviceaccount.com"